name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests (attempt 1)
        id: test-attempt-1
        run: bun run test
        continue-on-error: true

      - name: Run tests (attempt 2)
        if: steps.test-attempt-1.outcome == 'failure'
        run: bun run test
